[project]
name = "rail-network"
version = "0.1.0"
description = "Processing data with dbt and DuckDB"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core==1.9.3",
    "dbt-duckdb==1.9.2",
    "duckdb==1.2.1",
    "sqlfluff==3.3.1",
]
